#paste your code here:
from turtle import *
speed(10)
def haha (x, y, length) :
  bgcolor('black')
  penup()
  goto(x, y)
  pendown()
  color('darkgoldenrod')
  fillcolor('gold')
  begin_fill()
  for i in range(5):
    forward(length)
    left(108)
    forward(length)
    right(36)
  end_fill()
  penup()
  
  
  forward(length)
  left(108)
  forward(length/2)
  right(90)
  
  fillcolor ('coral')
  pencolor('firebrick')
  begin_fill()
  pendown()
  forward(2*length)
  left(144)
  forward(length)
  right(72)
  forward(length)
  left(144)
  forward(2*length)
  end_fill()
  
  penup()
  right(180)
  pencolor('darkgreen')
  fillcolor('olivedrab')
  begin_fill()
  pendown()
  forward(3*length)
  left(144)
  forward(length)
  right(90)
  forward(length)
  left(144)
  forward(3*length)
  end_fill()
  
  penup()
  right(180)
  pencolor('steelblue')
  fillcolor('lightskyblue')
  pendown()
  begin_fill()
  pendown()
  forward(2.5*length)
  left(144)
  forward(length)
  right(80)
  forward(length)
  left(144)
  forward(2.5*length)
  end_fill()
  
  left(90)
  
  penup()
  goto(x, y)
  pendown()
  color('darkgoldenrod')
  fillcolor('gold')
  begin_fill()
  for i in range(5):
    forward(length)
    left(108)
    forward(length)
    right(36)
  end_fill()
  penup()

  
haha(-10, -65, 50) 

