#paste your code here:
from turtle import *
speed(0)
violet = 7
bgcolor("black")
for i in range(violet): 
  pensize(7)
  pencolor("blue")
  circle(20+i*7)
  penup()
  right(90)
  forward(2+i*0.07)
  pendown()
  pencolor('turquoise')
  circle(15+i*7)
  penup()
  right(90)
  forward(2+i*0.07)
  left(90)
  pendown()
  pencolor('red')
  circle(10+i*7)
  penup()
  right(90)
  forward(2+i*0.07)
  left(90)
  pendown()
  pencolor('orange')
  circle(5+i*7)
  penup()
  right(90)
  forward(2+i*0.07)
  left(90)
  pendown()
  forward(50)

