#paste your code here:
from turtle import *
speed(10)
bgcolor('black')
pencolor('lightblue')
#the angle to turn is 360 divided by the number of shapes
degrees = 30 
length = 60
forward(length)
backward(length)
left(30)
penup()
forward(length)
left(90)
pendown()
forward(length)
left(90)
forward(length)
left(90)
forward(length)
right(90)
forward(length)
left(90)
forward(length)
left(90)
forward(length)
penup()
right(90)
forward(length)
pendown()
left(90)
forward(length*2)
left(90)
forward(length*4)
left(90)
forward(length*4)
left(90)
forward(length*4)
left(90)
forward(length*4)
