#paste your code here:

from turtle import *
speed(20)
pensize(16)
pencolor('blue')
def hexagon(size):
  angle = 360/6
  for i in range(26):
    
    forward(size)
    circle(30)
    left(20)
    forward(size)
    left(angle)
    left(20)
    forward(size)
    left(20)
    forward(size)
    right(angle)
    left(20)
    forward(size)
    left(angle)
    left(20)
    pencolor('white')
    forward(size)
    left(angle)
    left(20)
    pendown()
    forward(size)
    left(angle)
    penup()
    left(20)
    forward(size)
    left(angle)
    left(20)
    forward(size)
    left(angle)
    left(20)
    pencolor('green')
    pendown()
    forward(size)
    pensize(20)
    right(angle)
    penup()
    pencolor('pink')
    left(20)
    forward(size)
    left(angle)
    circle(30)
    left(20)
    forward(size)
    left(angle)
    left(20)
    pencolor('blue')
    right(45)
    pendown()
    forward(size)
    left(angle)
    left(20)
    forward(size)
    left(angle)
    left(20)
    forward(size)
    pencolor('red')
    left(angle)
    circle(30)
    left(20)
    forward(size)
    right(angle)
    fillcolor('pink')
begin_fill()    
bgcolor('black')
fillcolor('pink')
for i in range (26):
  hexagon(26)
  right(360/3)
end_fill()

