#paste your code here:
from turtle import *
speed(11)
penup()
forward(100)
pendown()
bgcolor('black')
for side in range(100, 40, -10):
  pensize(5)
  pencolor('skyblue')
  backward(side)
  left(90)
  forward(side)
  right(135)
  forward((side) * 2**.5)
  left(135)
  penup()
  forward(10)
  pendown()
  right(90)
  pendown()
penup()
right(90)
forward(60)
left(90)
backward(200)
left(180)
pendown()
for side in range(100, 40, -10):
  pensize(5)
  pencolor('skyblue')
  backward(side)
  left(90)
  forward(side)
  right(135)
  forward((side) * 2**.5)
  left(135)
  penup()
  forward(10)
  pendown()
  right(90)
  pendown()
penup()
goto(0, 0)
pensize(5)
right(45)
pendown()
pencolor('white')
forward(100)
for radius in range(5, 30, 5):
  fillcolor('black')
  begin_fill()
  circle(radius)
  end_fill()
  right(180)
  fillcolor('red')
  begin_fill()
  circle(radius)
  end_fill()
  right(180)
  backward(radius + 5)
right(180)
forward(100)
for radius in range(5, 30, 5):
  fillcolor('black')
  begin_fill()
  circle(radius)
  end_fill()
  right(180)
  fillcolor('red')
  begin_fill()
  circle(radius)
  end_fill()
  right(180)
  backward(radius + 5)


