#paste your code here:
from turtle import *
number = 7
number = 3
speed(10)
cc = 0
dd = 0
penup()
goto(0, 0)
pendown()
bgcolor('black')

def tri(x,y):
  goto(x,y)
  rn = random.randint(1, 255)
  bn = random.randint(1, 255)
  cn = random.randint(1, 255)
  pendown()
  pencolor(rn, bn, cn)
  pensize(5)
  fillcolor(rn, bn, cn)
  begin_fill()
  left(60)
  forward(90)
  left(120)
  forward(90)
  left(120)
  forward(90)
  end_fill()
  pencolor('white')
  penup()
  left(120)
  forward(45)
  pendown()
  fillcolor('white')
  begin_fill()
  left(60)
  forward(45)
  left(120)
  forward(45)
  left(120)
  forward(45)
  end_fill()
  penup()

def trian(x,y):
  goto(x,y)
  rn = random.randint(1, 255)
  bn = random.randint(1, 255)
  cn = random.randint(1, 255)
  pendown()
  pencolor(rn, bn, cn)
  pensize(5)
  fillcolor(rn, bn, cn)
  begin_fill()
  left(60)
  forward(90)
  right(120)
  forward(90)
  right(120)
  forward(90)
  end_fill()
  pencolor('white')
  penup()
  right(120)
  forward(45)
  pendown()
  fillcolor('white')
  begin_fill()
  right(60)
  forward(45)
  right(120)
  forward(45)
  right(120)
  forward(45)
  end_fill()
  penup()

for f in range(3):
  rn = random.randint(1, 255)
  bn = random.randint(1, 255)
  cn = random.randint(1, 255)
  fillcolor(rn, bn, cn)
  begin_fill()
  pencolor(rn, bn, cn)
  pensize(2)
  circle(85)
  cc = cc + 40
  dd = dd - 40
  end_fill()
  penup()
  goto(cc, dd)
  pendown()
  
penup()
goto(-40, -40)
cc = -40
dd = -40
pendown()
for f in range(2):
  rn = random.randint(1, 255)
  bn = random.randint(1, 255)
  cn = random.randint(1, 255)
  fillcolor(rn, bn, cn)
  begin_fill()
  pencolor(rn, bn, cn)
  pensize(2)
  circle(85)
  cc = cc - 40
  dd = dd - 40
  end_fill()
  penup()
  goto(cc, dd)
  pendown()
penup()
goto(-20, -20)
pendown()
tri(0, -40)
penup()
trian(-105,-40)
trian(105,-40)
trian(0,130)

